-- 009-portal-narrations.sql
-- Pre-rendered spoken narration per portal, per locale.
-- The narration text is generated by Mistral (stored in portal_scenes.scene_config
-- under a `narration` block); this table holds the melotts-rendered AUDIO so
-- playback is instant (no on-demand TTS call per visit).
--
-- One row per (portal_id, locale). Regenerated when the architect refreshes
-- a portal's scene (enhance_scene / birth_portal).
CREATE TABLE IF NOT EXISTS portal_narrations (
    portal_id     TEXT NOT NULL,
    locale        TEXT NOT NULL,          -- 'es' | 'en' | 'fr'
    audio_base64  TEXT,                   -- base64-encoded mp3 from melotts
    text_passage  TEXT,                   -- the spoken passage (for subtitles)
    generated_at  TIMESTAMP,
    PRIMARY KEY (portal_id, locale)
);
